package com.generation.thunderdev.contigo.model;

// Generated 2 may. 2022 21:13:49 by Hibernate Tools 5.6.7.Final

/**
 * EmocionCat generated by hbm2java
 */
public class EmocionCat implements java.io.Serializable {

	private int idemocionCat;
	private String emocion;
	private String color;

	public EmocionCat() {
	}

	public EmocionCat(int idemocionCat, String emocion, String color) {
		this.idemocionCat = idemocionCat;
		this.emocion = emocion;
		this.color = color;
	}

	public int getIdemocionCat() {
		return this.idemocionCat;
	}

	public void setIdemocionCat(int idemocionCat) {
		this.idemocionCat = idemocionCat;
	}

	public String getEmocion() {
		return this.emocion;
	}

	public void setEmocion(String emocion) {
		this.emocion = emocion;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
